### ISSUE TITLE
Feature request: add tribe filter

### ISSUE THREAD

**Issue by stauciuc** [futurice/contacts-ui#4]
Hi,
Hope this is the right medium for feature requests, please do teach me if there's a better way.
One very common use for Contacts for me is finding a person's name when I know his face.
As it's a bit tedious to look through 300 names, the more categorisation I can use for filtering the pool, the better. Title helps, but still with "developer" I don't filter that much. Tribe filter would help much more, as I can trust tribe names to be accurate and limited in size. Maybe there's a way to go even further (for example how old they are in the company), but this could be the first step.
Note that face recognition will not help in this case, because I won't walk up to that person and take a photo so that I can find out their name... 
Thanks,
Sebi

**Comment by phadej** [comment]
As commented in https://github.com/futurice/contacts-ui/issues/3#issuecomment-251106121, yes, tribe info would be great, and it's possible to add (need to add PlanMill integration for that).

However, *how old they are in the company* -question is currently impossible to answer, as we don't have that information in machine readable form anywhere.

**Comment by phadej** [comment]
There is tribe column now. Will add to filter ASAP, closing this issue nevertheless.
