### ISSUE TITLE
Row count

### ISSUE THREAD

**Issue by stauciuc** [futurice/contacts-ui#5]
Oh, it would be so unbelievably exquisite to be able to know how many people work at Futurice (more or less). With a simple row count you could be the ones to solve this perpetual mystery!

**Comment by phadej** [comment]
Note, there are externals as well, but I guess I can count both

**Comment by stauciuc** [comment]
wow, prompt answer and everything, thanks! 👍

**Comment by phadej** [comment]
*There are 350 futuriceans and 56 externals.*

You might need to force reload (shift+cmd+r) to invalidate caches.
